// <auto-generated />
using GTUGraphicsModule.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTUGraphicsModule.API.Migrations
{
    [DbContext(typeof(GTUGraphicsModuleDbContext))]
    [Migration("20240215080032_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kalite_Birim");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_Konu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KonuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kalite_Konu");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeBirimIliski", b =>
                {
                    b.Property<int>("ef_gereksinimi_icin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ef_gereksinimi_icin_id"));

                    b.Property<int>("baslangic_ticks")
                        .HasColumnType("int");

                    b.Property<int>("birim_id")
                        .HasColumnType("int");

                    b.Property<int>("bitis_ticks")
                        .HasColumnType("int");

                    b.Property<int>("performans_gosterge_id")
                        .HasColumnType("int");

                    b.HasKey("ef_gereksinimi_icin_id");

                    b.HasIndex("birim_id");

                    b.HasIndex("performans_gosterge_id");

                    b.ToTable("Kalite_PerformansGostergeBirimIliski");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeGerceklesenDeger", b =>
                {
                    b.Property<int>("performans_gosterge_id")
                        .HasColumnType("int");

                    b.Property<int>("faaliyet_donem_id")
                        .HasColumnType("int");

                    b.Property<int>("surec_id")
                        .HasColumnType("int");

                    b.Property<int>("periyod")
                        .HasColumnType("int");

                    b.Property<int>("gerceklesen_deger")
                        .HasColumnType("int");

                    b.HasKey("performans_gosterge_id", "faaliyet_donem_id", "surec_id", "periyod");

                    b.ToTable("Kalite_PerformansGostergeGerceklesenDeger");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeHedeflenenDeger", b =>
                {
                    b.Property<int>("performans_gosterge_id")
                        .HasColumnType("int");

                    b.Property<int>("faaliyet_donem_id")
                        .HasColumnType("int");

                    b.Property<int>("surec_id")
                        .HasColumnType("int");

                    b.Property<int>("hedeflenen_deger")
                        .HasColumnType("int");

                    b.HasKey("performans_gosterge_id", "faaliyet_donem_id", "surec_id");

                    b.HasIndex("performans_gosterge_id")
                        .IsUnique();

                    b.ToTable("Kalite_PerformansGostergeHedeflenenDeger");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeKonuIliski", b =>
                {
                    b.Property<int>("ef_gereksinimi_icin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ef_gereksinimi_icin_id"));

                    b.Property<int>("baslangic_ticks")
                        .HasColumnType("int");

                    b.Property<int>("bitis_ticks")
                        .HasColumnType("int");

                    b.Property<int>("konu_id")
                        .HasColumnType("int");

                    b.Property<int>("performans_gosterge_id")
                        .HasColumnType("int");

                    b.HasKey("ef_gereksinimi_icin_id");

                    b.HasIndex("konu_id");

                    b.HasIndex("performans_gosterge_id");

                    b.ToTable("Kalite_PerformansGostergeKonuIliski");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Kalite_PerformansGostergeTanim");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim_Revizyon", b =>
                {
                    b.Property<int>("_ef_gereksinimi_icin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_ef_gereksinimi_icin_id"));

                    b.Property<int>("_silinecek_formul_cesit")
                        .HasColumnType("int");

                    b.Property<int>("_silinecek_genel_gosterge_formul_cesit")
                        .HasColumnType("int");

                    b.Property<int>("_silinecek_gosterge_cesit")
                        .HasColumnType("int");

                    b.Property<int>("_silinecek_sonuc_kriter_cesit")
                        .HasColumnType("int");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_ingilizce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("aktif")
                        .HasColumnType("bit");

                    b.Property<int>("baslangic_ticks")
                        .HasColumnType("int");

                    b.Property<int>("bitis_ticks")
                        .HasColumnType("int");

                    b.Property<string>("eski_kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("formul_cesit")
                        .HasColumnType("int");

                    b.Property<int>("genel_gosterge_formul_cesit")
                        .HasColumnType("int");

                    b.Property<int>("izleme_periyot_cesit")
                        .HasColumnType("int");

                    b.Property<string>("kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("olcu_birim_cesit")
                        .HasColumnType("int");

                    b.Property<int>("performans_gosterge_tanim_id")
                        .HasColumnType("int");

                    b.Property<int>("revizyon_numarasi")
                        .HasColumnType("int");

                    b.Property<int>("strateji_id")
                        .HasColumnType("int");

                    b.Property<string>("tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_ef_gereksinimi_icin_id");

                    b.HasIndex("performans_gosterge_tanim_id");

                    b.ToTable("Kalite_PerformansGostergeTanim_Revizyon");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeVeriKategorisiIliski", b =>
                {
                    b.Property<int>("ef_gereksinimi_icin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ef_gereksinimi_icin_id"));

                    b.Property<int>("baslangic_ticks")
                        .HasColumnType("int");

                    b.Property<int>("bitis_ticks")
                        .HasColumnType("int");

                    b.Property<int>("performans_gosterge_id")
                        .HasColumnType("int");

                    b.Property<int>("veri_kategorisi_id")
                        .HasColumnType("int");

                    b.HasKey("ef_gereksinimi_icin_id");

                    b.HasIndex("performans_gosterge_id");

                    b.HasIndex("veri_kategorisi_id");

                    b.ToTable("Kalite_PerformansGostergeVeriKategorisiIliski");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_VeriKategorileri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("VeriKategorileri");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_VeriKategorileri_Revizyon", b =>
                {
                    b.Property<int>("ef_gereksininmi_icin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ef_gereksininmi_icin_id"));

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("baslangic_ticks")
                        .HasColumnType("int");

                    b.Property<int>("bitis_ticks")
                        .HasColumnType("int");

                    b.Property<string>("kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ust_veri_kategorisi_id")
                        .HasColumnType("int");

                    b.Property<int>("veri_kategorisi_id")
                        .HasColumnType("int");

                    b.HasKey("ef_gereksininmi_icin_id");

                    b.HasIndex("ust_veri_kategorisi_id");

                    b.ToTable("VeriKategorileri_Revizyon");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeBirimIliski", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_Birim", "Kalite_Birim")
                        .WithMany()
                        .HasForeignKey("birim_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim", "Kalite_PerformansGostergeTanim")
                        .WithMany()
                        .HasForeignKey("performans_gosterge_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_Birim");

                    b.Navigation("Kalite_PerformansGostergeTanim");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeGerceklesenDeger", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeHedeflenenDeger", "Kalite_PerformansGostergeHedeflenenDeger")
                        .WithMany("Kalite_PerformansGostergeGerceklesenDeger")
                        .HasForeignKey("performans_gosterge_id", "faaliyet_donem_id", "surec_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_PerformansGostergeHedeflenenDeger");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeHedeflenenDeger", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim_Revizyon", "Kalite_PerformansGostergeTanim_Revizyon")
                        .WithOne("Kalite_PerformansGostergeHedeflenenDeger")
                        .HasForeignKey("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeHedeflenenDeger", "performans_gosterge_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_PerformansGostergeTanim_Revizyon");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeKonuIliski", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_Konu", "Kalite_Konu")
                        .WithMany()
                        .HasForeignKey("konu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim", "Kalite_PerformansGostergeTanim")
                        .WithMany()
                        .HasForeignKey("performans_gosterge_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_Konu");

                    b.Navigation("Kalite_PerformansGostergeTanim");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim_Revizyon", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim", "Kalite_PerformansGostergeTanim")
                        .WithMany()
                        .HasForeignKey("performans_gosterge_tanim_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_PerformansGostergeTanim");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeVeriKategorisiIliski", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim", "Kalite_PerformansGostergeTanim")
                        .WithMany()
                        .HasForeignKey("performans_gosterge_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_VeriKategorileri", "Kalite_VeriKategorileri")
                        .WithMany()
                        .HasForeignKey("veri_kategorisi_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_PerformansGostergeTanim");

                    b.Navigation("Kalite_VeriKategorileri");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_VeriKategorileri_Revizyon", b =>
                {
                    b.HasOne("GTUGraphicsModule.Models.Models.Kalite_VeriKategorileri", "Kalite_VeriKategorileri")
                        .WithMany()
                        .HasForeignKey("ust_veri_kategorisi_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalite_VeriKategorileri");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeHedeflenenDeger", b =>
                {
                    b.Navigation("Kalite_PerformansGostergeGerceklesenDeger");
                });

            modelBuilder.Entity("GTUGraphicsModule.Models.Models.Kalite_PerformansGostergeTanim_Revizyon", b =>
                {
                    b.Navigation("Kalite_PerformansGostergeHedeflenenDeger");
                });
#pragma warning restore 612, 618
        }
    }
}
